version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: gazincrud
      DB_USERNAME: root
      DB_PASSWORD: 

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: gazincrud
      MYSQL_USER: root
      MYSQL_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
    volumes:
      - ./mysql_data:/var/lib/mysql
